# fly.toml app configuration file generated for bunchatbot on 2023-09-12T14:35:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bunchatbot"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
