name: Deploy to fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="/home/runner/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"

    - name: Authenticate with Fly.io
      run: flyctl auth login -t ${{ secrets.FLY_API_TOKEN }}

    - name: Run deploy script
      run: ./deploy.sh
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
